# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OldPrint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('title_page_content', models.TextField(blank=True)),
                ('title_variant', models.CharField(blank=True, max_length=256)),
                ('author_khw', models.CharField(blank=True, max_length=64)),
                ('author_doc', models.CharField(blank=True, max_length=64)),
                ('publication_place', models.CharField(blank=True, max_length=32)),
                ('publisher_name', models.CharField(blank=True, max_length=128)),
                ('publication_date', models.DateField(blank=True)),
                ('printing_place', models.CharField(blank=True, max_length=32)),
                ('printing_house_name', models.CharField(blank=True, max_length=128)),
                ('printing_date', models.DateField(blank=True)),
                ('number_of_pages', models.IntegerField(blank=True)),
                ('designation_illustration', models.CharField(blank=True, max_length=32)),
                ('bibliography_format', models.CharField(blank=True, max_length=32)),
                ('ownership_entries', models.CharField(blank=True, max_length=512)),
                ('figerprint', models.CharField(blank=True, max_length=64)),
                ('other_information', models.TextField(blank=True)),
                ('co_founder', models.CharField(blank=True, max_length=128)),
                ('keywords', models.CharField(blank=True, max_length=256)),
                ('source_type', models.CharField(blank=True, max_length=128)),
                ('resource_identifier', models.CharField(blank=True, max_length=16)),
                ('e_format', models.CharField(blank=True, max_length=16)),
                ('source', models.CharField(blank=True, max_length=512)),
                ('language_code', models.CharField(blank=True, max_length=16)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('bookbinding_block', models.CharField(blank=True, max_length=16)),
                ('signature', models.CharField(blank=True, max_length=16)),
                ('laws', models.CharField(blank=True, max_length=16)),
                ('daten_od', models.DateField(blank=True)),
                ('daten_do', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.FilePathField()),
                ('old_print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prints.OldPrint')),
            ],
        ),
        migrations.AddField(
            model_name='oldprint',
            name='title_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prints.Scan'),
        ),
    ]
